const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },{
        src:'./images/kurly_003.jpg',
        name:'[오뚜기] 진비빔면 4개입',
        summary:'매콤달콤한 여름철 별미',
        price:3980,
        sale:10,
        review:231,
    },
    {
        src:'./images/kurly_004.jpg',
        name:'[빙그레] 바나나맛 우유 6입',
        summary:'국민 간식 바나나맛 우유',
        price:5200,
        sale:5,
        review:145,
    },
    {
        src:'./images/kurly_005.jpg',
        name:'[풀무원] 얇은피 꽉찬속 만두 1kg',
        summary:'피는 얇고 속은 가득!',
        price:8900,
        sale:15,
        review:98,
    },
    {
        src:'./images/kurly_006.jpg',
        name:'[CJ] 고메 함박스테이크 2입',
        summary:'두툼하고 육즙 가득한 함박',
        price:6800,
        sale:12,
        review:87,
    },
    {
        src:'./images/kurly_007.jpg',
        name:'[샘표] 진간장 금S 930ml',
        summary:'깊고 진한 국산 간장',
        price:3180,
        sale:8,
        review:42,
    },
    {
        src:'./images/kurly_008.jpg',
        name:'[초코송이] 여름 한정 민트맛',
        summary:'상쾌한 민트의 달콤한 변신',
        price:1980,
        sale:10,
        review:76,
    },
    {
        src:'./images/kurly_009.jpg',
        name:'[농심] 신라면 블랙 컵 6개입',
        summary:'진한 국물의 프리미엄 컵라면',
        price:6900,
        sale:13,
        review:203,
    },
    {
        src:'./images/kurly_010.jpg',
        name:'[서울우유] 나100% 우유 1L',
        summary:'신선함이 살아있는 우유',
        price:2500,
        sale:5,
        review:321,
    },
    {
        src:'./images/kurly_011.jpg',
        name:'[더반찬] 삼겹살 김치찜 600g',
        summary:'밥도둑 김치찜의 정석',
        price:11900,
        sale:17,
        review:65,
    },
    {
        src:'./images/kurly_012.jpg',
        name:'[모노키친] 통등심 돈카츠 2장',
        summary:'겉바속촉 제대로 만든 돈카츠',
        price:7800,
        sale:9,
        review:112,
    },
]